### ISSUE TITLE
关于v-tooltips的一些问题

### ISSUE THREAD

**Issue by fengdygaga** [Gesj-yean/vue-demo-collection#3]
`function structureIcon(content, attrs) {
  
let attrStr = ''
  for (const key in attrs) {
    attrStr += `${key}=${attrs[key]} `
  }
  const a = `<el-tooltip content=${content} ${attrStr}>
  <i class="el-icon-question" style="margin:0 10px"></i></el-tooltip>`
  const Tooltip = Vue.extend({
    template: a
  })
  const component = new Tooltip().$mount()
  return component.$el
}`

上面的代码是v-tooltip里面的
想问下作者 这个template写法改成render写法 应该怎么写 
刚入门vue请大佬指点一下

**Comment by Gesj-yean** [comment]
function structureIcon (content, attrs) {
  // 创建构造器
  const tooltip = Vue.extend({
    render: (h) => (
      <el-tooltip content={content} {...attrs}><i class="el-icon-question" style="margin:0 10px"></i></el-tooltip>
    )
  })
  // 创建一个 tooltip 实例并返回 dom 节点
  const component = new tooltip().$mount()
  return component.$el
}

**Comment by Gesj-yeah** [comment]
function structureIcon (content, attrs) {
// 创建构造器
const tooltip = Vue.extend({
render: (h) => (
<el-tooltip content={content} {...attrs}>
)
})
// 创建一个 tooltip 实例并返回 dom 节点
const component = new tooltip().$mount()
return component.$el
}

**Comment by Gesj-yeah** [comment]
function structureIcon (content, attrs) {
 // 创建构造器
 const tooltip = Vue.extend({
 render: (h) => (
 <el-tooltip content={content} {...attrs}>
 )
 })
 // 创建一个 tooltip 实例并返回 dom 节点
 const component = new tooltip().$mount()
 return component.$el
}


在 2021年5月20日 ***@***.***> 写道：


function structureIcon(content, attrs) { let attrStr = '' for (const key in attrs) { attrStr += ${key}=${attrs[key]} } const a =<el-tooltip content=${content} ${attrStr}>
 const Tooltip = Vue.extend({ template: a }) const component = new Tooltip().$mount() return component.$el }
上面的代码是v-tooltip里面的
 想问下作者 这个template写法改成render写法 应该怎么写
 刚入门vue请大佬指点一下
